#!/usr/bin/env node

require('proof')(0, function (assert) {
    var hilbert = require('../..')
    console.log('right rotation')
    console.log("1 should rotate to 4. It is " + hilbert.rotr(1,2,3))
    console.log("2 should rotate to 1. It is " + hilbert.rotr(2,2,3))
    console.log("3 should rotate to 5. It is " + hilbert.rotr(3,2,3))
    console.log("4 should rotate to 2. It is " + hilbert.rotr(4,2,3))
    console.log("5 should rotate to 6. It is " + hilbert.rotr(5,2,3))
    console.log("6 should rotate to 3. It is " + hilbert.rotr(6,2,3))
    console.log("7 should rotate to 7. It is " + hilbert.rotr(7,2,3))

    console.log('left rotation')
    console.log("1 should rotate to 2. It is " + hilbert.rotl(1,2,3))
    console.log("2 should rotate to 4. It is " + hilbert.rotl(2,2,3))
    console.log("3 should rotate to 6. It is " + hilbert.rotl(3,2,3))
    console.log("4 should rotate to 1. It is " + hilbert.rotl(4,2,3))
    console.log("5 should rotate to 3. It is " + hilbert.rotl(5,2,3))
    console.log("6 should rotate to 5. It is " + hilbert.rotl(6,2,3))
    console.log("7 should rotate to 7. It is " + hilbert.rotl(7,2,3))
    hilbert.rotl(1,2,3)
    hilbert.rotl(3,2,3)
    hilbert.rotl(5,2,3)
    hilbert.rotl(7,2,3)
    hilbert.rotl(2,2,3)
    hilbert.rotl(4,2,3)
    hilbert.rotl(6,2,3)
    hilbert.rotr(1,2,3)
    hilbert.rotr(3,2,3)
    hilbert.rotr(5,2,3)
    hilbert.rotr(2,2,3)
    hilbert.rotr(4,2,3)
    hilbert.rotr(6,2,3)
    //equal(hilbert.xy2d(4, 0, 2), 16)
    //assert(hilbert.xy2d(16, 2, 2), 8)
    //assert(hilbert.xy2d(0, 0, 2), 0)
    //assert(hilbert.xy2d(0, 1, 3), 1)
    console.log(hilbert.hilbert(2, 5, 6))
    hilbert.hilbert(2, 5, 6)
})
